FROM alpine:3.1

#update
RUN apk add --update python py-pip

#Install all dependencies

RUN pip install logging
RUN pip install datetime
RUN pip install BeautifulSoup4
RUN pip install requests

#Bundle app source
COPY Problem_1.py /src/Problem_1.py 

EXPOSE 8000
CMD ["python", "/src/Problem_1.py", "-p 8000"]
